# Question 1
#Write a Numpy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [2]:
import numpy as np
x=np.random.randint(0,11,5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[5 3 6 3 8]


# Question 2
#Write a Numpy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [3]:
import numpy as np 
V=np.arange (15,55)
print("Original Vector:")
print(V)
print("All values except the first and last of the said vector:")
print(V[1:-1])

Original Vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


# Question 3
#Write a Numpy program to create a random array with 1000 elements and compute tha average, variance,standard deviation of the array elements.

In [4]:
import numpy as np
x = np.random.randn(1000)
print("Average of the array elements:")
mean = x.mean()
print(mean)
print("Standard deviation of the array elements:")
std = x.std()
print(std)
print("Variance of the array elements:")
var = x.var()
print(var)

Average of the array elements:
0.026918071202675885
Standard deviation of the array elements:
0.9927584179305772
Variance of the array elements:
0.9855692763720226


# Question 4
#Write a Numpy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the rows of a given 3x3

In [5]:
import numpy as np
Z=np.array([[1,2,3], [4,5,6]])
print("Original array:")
print(Z)
print("Cumulative sum of the elements along a given axis:")
X=np.cumsum(Z)
print(X)
print("\nSum over rows for each of the 3 columns:")
X=np.cumsum(Z,axis=0)
print(X)
print("\nSum over columns for each of the 2 rows:")
X=np.cumsum(Z,axis=1)
print(X)

Original array:
[[1 2 3]
 [4 5 6]]
Cumulative sum of the elements along a given axis:
[ 1  3  6 10 15 21]

Sum over rows for each of the 3 columns:
[[1 2 3]
 [5 7 9]]

Sum over columns for each of the 2 rows:
[[ 1  3  6]
 [ 4  9 15]]


# Question 5
#Write a Numpy program to compute the multiplication of two given matrixes. Sample Matrix: [[1,0],[0,1]] [[1,2],[3,4]]

In [6]:
import numpy as np
C=[[1,0],[0,1]]
A=[[1,2],[3,4]]
print("original matrix:")
print(C)
print(A)
result_1=np.dot(C,A)
print("Result of the said matrix multipication:")
print(result_1)


original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multipication:
[[1 2]
 [3 4]]
